version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: ai_hub
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  mysql-data: