version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: ai_hub
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  backend:
    build:
      context: ../ai-hub-server
      dockerfile: Dockerfile
  frontend:
    build:
      context: ../ai-hub-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  mysql-data: